// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCewCuFi9EotoPWRiYHdPhmBzrQ_yd0VAU',
    appId: '1:414576587934:web:8033c733755764f161778f',
    messagingSenderId: '414576587934',
    projectId: 'matchbet-46416',
    authDomain: 'matchbet-46416.firebaseapp.com',
    storageBucket: 'matchbet-46416.appspot.com',
    measurementId: 'G-HWX4VY7ZTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXJW-3Un81Us8wBNtvjP1qZk0oicebcO4',
    appId: '1:414576587934:android:0f3c839af01095c061778f',
    messagingSenderId: '414576587934',
    projectId: 'matchbet-46416',
    storageBucket: 'matchbet-46416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_fn5I38-8FcM-pPxoEJrD4s7JOHTD6Fg',
    appId: '1:414576587934:ios:a6193d46c4f5dd5e61778f',
    messagingSenderId: '414576587934',
    projectId: 'matchbet-46416',
    storageBucket: 'matchbet-46416.appspot.com',
    iosBundleId: 'com.frezycode.matchBet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_fn5I38-8FcM-pPxoEJrD4s7JOHTD6Fg',
    appId: '1:414576587934:ios:82ff828bed29af6c61778f',
    messagingSenderId: '414576587934',
    projectId: 'matchbet-46416',
    storageBucket: 'matchbet-46416.appspot.com',
    iosBundleId: 'com.frezycode.matchBet.RunnerTests',
  );
}
